CMTPATH=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline:/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper:/home/hep/david_moore/zl423/NEXOTOP/nexo-ei
CMT_tag=$(tag)
CMTROOT=/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/CMT/v1r26
CMT_root=/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/InstallArea/${CMTCONFIG}/bin:/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/InstallArea/${CMTCONFIG}/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/CMT/v1r26/${CMTBIN}:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/vgm/4.3/bin:/home/hep/david_moore/zl423/geant4_workdir/bin/Linux-g++:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Geant4/10.00.p01/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/ROOT/5.34.36/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/GCCXML/master/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Xercesc/3.1.2/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/SoXt/1.3.0/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Coin/3.1.3/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/gsl/1.16/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Cmake/2.8.12.1/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Boost/1.55.0/bin:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Python/2.7.11/bin:/home/hep/david_moore/zl423/geant4/bin:/apps/hpc/Libs/QT/4.8.6/bin:/usr/local/cluster/hpc/Langs/Python/2.7.10/bin:/usr/local/cluster/hpc/Langs/TCLTK/8.5.14/bin:/usr/NX/bin:/apps/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/hep/share/cernlib/2006b/x86_64-slc5-gcc41-opt/bin:/home/hep/share/app/gv/bin:/home/hep/share/app/nedit:/home/hep/share/app/sm/bin:/home/hep/share/app/bin:/home/hep/david_moore/zl423/bin
CLASSPATH=/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-fPIC -pipe -ansi -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-rhel72-gcc485
tutorials_tag=$(tag)
TUTORIALSROOT=/home/hep/david_moore/zl423/NEXOTOP/tutorials
tutorials_root=/home/hep/david_moore/zl423/NEXOTOP/tutorials
TUTORIALSVERSION=v0
tutorials_offset=/home/hep/david_moore/zl423/NEXOTOP
SniperRelease_tag=$(tag)
SNIPERRELEASEROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperRelease
SniperRelease_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperRelease
SNIPERRELEASEVERSION=v2
SniperRelease_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
SniperRelease_project=nexo-sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperPolicy
SniperPolicy_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
SniperPolicy_project=nexo-sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperKernel
SniperKernel_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
SniperKernel_project=nexo-sniper
Boost_tag=$(tag)
BOOSTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/Boost
Boost_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei
Boost_offset=Externals
Boost_project=nexo-ei
Python_tag=$(tag)
PYTHONROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/Python
Python_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei
Python_offset=Externals
Python_project=nexo-ei
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${NEXO_EXTLIB_Boost_HOME}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python 
includes= $(ppcmd)"$(srcdir)" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/InstallArea/include" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/InstallArea/python:/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/InstallArea/python:/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/InstallArea/Linux-x86_64/lib:/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/InstallArea/Linux-x86_64/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/ROOT/5.34.36/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Python/2.7.11/lib/./python2.7/lib-dynload
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
DataBuffer_tag=$(tag)
DATABUFFERROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperUtil/DataBuffer
DataBuffer_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperUtil/DataBuffer
DATABUFFERVERSION=v0
DataBuffer_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
DataBuffer_offset=SniperUtil
DataBuffer_project=nexo-sniper
HelloWorld_tag=$(tag)
HELLOWORLDROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/Examples/HelloWorld
HelloWorld_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/Examples/HelloWorld
HELLOWORLDVERSION=v1
HelloWorld_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
HelloWorld_offset=Examples
HelloWorld_project=nexo-sniper
RootWriter_tag=$(tag)
ROOTWRITERROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperSvc/RootWriter
RootWriter_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/SniperSvc/RootWriter
ROOTWRITERVERSION=v0
RootWriter_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
RootWriter_offset=SniperSvc
RootWriter_project=nexo-sniper
ROOT_tag=$(tag)
ROOTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/ROOT
ROOT_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei
ROOT_offset=Externals
ROOT_project=nexo-ei
ROOT_home=${NEXO_EXTLIB_ROOT_HOME}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --evelibs` -lPyROOT 
rootcint="$(ROOT_home)/bin/rootcint"
RootWriter_linkopts= -lRootWriter 
RootWriter_stamps=${ROOTWRITERROOT}/${BINDIR}/RootWriter.stamp 
RootWriter_linker_library=RootWriter
DummyAlg_tag=$(tag)
DUMMYALGROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/Examples/DummyAlg
DummyAlg_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/Examples/DummyAlg
DUMMYALGVERSION=v0
DummyAlg_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
DummyAlg_offset=Examples
DummyAlg_project=nexo-sniper
EvtNavigator_tag=$(tag)
EVTNAVIGATORROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EvtNavigator
EvtNavigator_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EvtNavigator
EVTNAVIGATORVERSION=v0
EvtNavigator_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
EvtNavigator_offset=DataModel
EvtNavigator_project=nexo-offline
BaseEvent_tag=$(tag)
BASEEVENTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/BaseEvent
BaseEvent_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/BaseEvent
BASEEVENTVERSION=v0
BaseEvent_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
BaseEvent_offset=DataModel
BaseEvent_project=nexo-offline
XmlObjDesc_tag=$(tag)
XMLOBJDESCROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/XmlObjDesc
XmlObjDesc_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/XmlObjDesc
XMLOBJDESCVERSION=v0
XmlObjDesc_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
XmlObjDesc_project=nexo-offline
xmlsrc=xml
XODflags= -n nEXO 
BaseEvent_dependencies= BaseEventObj2Doth  BaseEventDict  BaseEventxodsrc 
install_more_includes_dependencies= BaseEventObj2Doth 
BaseEventDict_dependencies= BaseEventObj2Doth  install_more_includes 
BaseEventxodsrc_dependencies= BaseEventObj2Doth 
BaseEvent_linkopts= -lBaseEvent 
BaseEvent_stamps=${BASEEVENTROOT}/${BINDIR}/BaseEvent.stamp 
BaseEvent_linker_library=BaseEvent
EDMUtil_tag=$(tag)
EDMUTILROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EDMUtil
EDMUtil_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EDMUtil
EDMUTILVERSION=v0
EDMUtil_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
EDMUtil_offset=DataModel
EDMUtil_project=nexo-offline
EDMUtil_dependencies= EDMUtilDict  EDMUtilDict  EDMUtilDict  EDMUtilDict 
EDMUtilDict_dependencies= EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes 
EDMUtil_linkopts= -lEDMUtil 
EDMUtil_stamps=${EDMUTILROOT}/${BINDIR}/EDMUtil.stamp 
EDMUtil_linker_library=EDMUtil
EvtNavigator_cintflags=-I$(CMTINSTALLAREA)/include
EvtNavigator_dependencies= EvtNavigatorDict 
EvtNavigatorDict_dependencies= EvtNavigatorObj2Doth  install_more_includes 
EvtNavigator_linkopts= -lEvtNavigator 
EvtNavigator_stamps=${EVTNAVIGATORROOT}/${BINDIR}/EvtNavigator.stamp 
EvtNavigator_linker_library=EvtNavigator
SimEvent_tag=$(tag)
SIMEVENTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/SimEvent
SimEvent_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/SimEvent
SIMEVENTVERSION=v0
SimEvent_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
SimEvent_offset=DataModel
SimEvent_project=nexo-offline
SimEvent_cintflags= -I$(SIMEVENTROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
SimHeader_cintflags= $(SimEvent_cintflags) 
SimEvent_dependencies= SimEventDict  SimEventDict 
SimEventDict_dependencies= SimEventObj2Doth  install_more_includes  SimEventObj2Doth  install_more_includes 
SimEvent_linkopts= -lSimEvent 
SimEvent_stamps=${SIMEVENTROOT}/${BINDIR}/SimEvent.stamp 
SimEvent_linker_library=SimEvent
ElecEvent_tag=$(tag)
ELECEVENTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/ElecEvent
ElecEvent_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/ElecEvent
ELECEVENTVERSION=v0
ElecEvent_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
ElecEvent_offset=DataModel
ElecEvent_project=nexo-offline
ElecEvent_cintflags= -I$(ELECEVENTROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
ElecHeader_cintflags= $(ElecEvent_cintflags) 
ElecEvent_dependencies= ElecEventDict  ElecEventDict  ElecEventDict 
ElecEventDict_dependencies= ElecEventObj2Doth  install_more_includes  ElecEventObj2Doth  install_more_includes  ElecEventObj2Doth  install_more_includes 
ElecEvent_linkopts= -lElecEvent 
ElecEvent_stamps=${ELECEVENTROOT}/${BINDIR}/ElecEvent.stamp 
ElecEvent_linker_library=ElecEvent
PidTmvaEvent_tag=$(tag)
PIDTMVAEVENTROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/PidTmvaEvent
PidTmvaEvent_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/PidTmvaEvent
PIDTMVAEVENTVERSION=v0
PidTmvaEvent_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
PidTmvaEvent_offset=DataModel
PidTmvaEvent_project=nexo-offline
PidTmvaEvent_cintflags= -I$(PIDTMVAEVENTROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
PidTmvaHeader_cintflags= $(PidTmvaEvent_cintflags) 
PidTmvaEvent_dependencies= PidTmvaEventDict  PidTmvaEventDict 
PidTmvaEventDict_dependencies= PidTmvaEventObj2Doth  install_more_includes  PidTmvaEventObj2Doth  install_more_includes 
PidTmvaEvent_linkopts= -lPidTmvaEvent 
PidTmvaEvent_stamps=${PIDTMVAEVENTROOT}/${BINDIR}/PidTmvaEvent.stamp 
PidTmvaEvent_linker_library=PidTmvaEvent
BufferMemMgr_tag=$(tag)
BUFFERMEMMGRROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/CommonSvc/BufferMemMgr
BufferMemMgr_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/CommonSvc/BufferMemMgr
BUFFERMEMMGRVERSION=v0
BufferMemMgr_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
BufferMemMgr_offset=CommonSvc
BufferMemMgr_project=nexo-offline
RootIOSvc_tag=$(tag)
ROOTIOSVCROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/RootIO/RootIOSvc
RootIOSvc_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/RootIO/RootIOSvc
ROOTIOSVCVERSION=v0
RootIOSvc_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
RootIOSvc_offset=RootIO
RootIOSvc_project=nexo-offline
RootIOUtil_tag=$(tag)
ROOTIOUTILROOT=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/RootIO/RootIOUtil
RootIOUtil_root=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/RootIO/RootIOUtil
ROOTIOUTILVERSION=v0
RootIOUtil_cmtpath=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
RootIOUtil_offset=RootIO
RootIOUtil_project=nexo-offline
RootIOUtil_linkopts= -lRootIOUtil 
RootIOUtil_stamps=${ROOTIOUTILROOT}/${BINDIR}/RootIOUtil.stamp 
RootIOUtil_linker_library=RootIOUtil
RootIOSvc_linkopts= -lRootIOSvc 
RootIOSvc_stamps=${ROOTIOSVCROOT}/${BINDIR}/RootIOSvc.stamp 
RootIOSvc_linker_library=RootIOSvc
BufferMemMgr_linkopts= -lBufferMemMgr 
BufferMemMgr_stamps=${BUFFERMEMMGRROOT}/${BINDIR}/BufferMemMgr.stamp 
BufferMemMgr_linker_library=BufferMemMgr
tutorials_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(tutorials_use_linkopts)
tutorials_use_linkopts=    $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(DummyAlg_linkopts)  $(RootWriter_linkopts)  $(BufferMemMgr_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(SimEvent_linkopts)  $(ElecEvent_linkopts)  $(PidTmvaEvent_linkopts)  $(EDMUtil_linkopts)  $(SniperKernel_linkopts)  $(BaseEvent_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts) 
tutorials_stamps=${TUTORIALSROOT}/${BINDIR}/tutorials.stamp 
tutorials_linker_library=tutorials
tag=Linux-x86_64
package=tutorials
version=v0
PACKAGE_ROOT=$(TUTORIALSROOT)
srcdir=../src
bin=../$(tutorials_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/home/hep/david_moore/zl423/NEXOTOP/tutorials/Linux-x86_64/
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(nexo-sniper_installarea_prefix)/$(CMTCONFIG)/lib $(nexo-sniper_installarea_prefix)/share/lib $(nexo-sniper_installarea_prefix)/share/bin $(nexo-offline_installarea_prefix)/$(CMTCONFIG)/lib $(nexo-offline_installarea_prefix)/share/lib $(nexo-offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(tutorials_linkopts)  $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(DummyAlg_linkopts)  $(RootWriter_linkopts)  $(BufferMemMgr_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(SimEvent_linkopts)  $(ElecEvent_linkopts)  $(PidTmvaEvent_linkopts)  $(EDMUtil_linkopts)  $(SniperKernel_linkopts)  $(BaseEvent_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts) 
nexo-ei_installarea_prefix=$(cmt_installarea_prefix)
nexo-ei_installarea_prefix_remove=$(nexo-ei_installarea_prefix)
LD_LIBRARY_PATH=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/InstallArea/${CMTCONFIG}/lib:/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/InstallArea/${CMTCONFIG}/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/vgm/4.3/lib64:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Geant4/10.00.p01/lib64:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/ROOT/5.34.36/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Xercesc/3.1.2/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/SoXt/1.3.0/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Coin/3.1.3/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/gsl/1.16/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Boost/1.55.0/lib:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Python/2.7.11/lib:/home/hep/david_moore/zl423/geant4/lib64:/home/apps/fas/Langs/GCC/4.8.2/lib64:/home/apps/fas/Langs/GCC/4.8.2/lib:/apps/hpc/Libs/QT/4.8.6/lib:/usr/local/cluster/hpc/Langs/Python/2.7.10/lib:/usr/local/cluster/hpc/Langs/TCLTK/8.5.14/lib:/usr/NX/lib:/home/hep/share/app/lib:/home/hep/share/app/xpa/lib:/home/hep/share/app/BAT/lib:/home/hep/david_moore/zl423/vgm_build/lib64:/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/fftw-3.3.6-pl2/lib
nexo-sniper_installarea_prefix=$(cmt_installarea_prefix)
nexo-sniper_installarea_prefix_remove=$(nexo-sniper_installarea_prefix)
nexo-offline_installarea_prefix=$(cmt_installarea_prefix)
nexo-offline_installarea_prefix_remove=$(nexo-offline_installarea_prefix)
cmt_installarea_linkopts= -L/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/$(nexo-offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/$(nexo-sniper_installarea_prefix)/$(CMTCONFIG)/lib 
nexo-ei_home=/home/hep/david_moore/zl423/NEXOTOP/nexo-ei
nexo-sniper_home=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper
nexo-offline_home=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline
nexo-offline_install_include= /home/hep/david_moore/zl423/NEXOTOP/nexo-offline/$(nexo-offline_installarea_prefix)/include 
nexo-sniper_install_include= /home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/$(nexo-sniper_installarea_prefix)/include 
nexo-sniper_python_path=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/$(nexo-sniper_installarea_prefix)/$(tag)/lib
nexo-offline_python_path=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/$(nexo-offline_installarea_prefix)/$(tag)/lib
nexo-sniper_install_python=/home/hep/david_moore/zl423/NEXOTOP/nexo-sniper/$(nexo-sniper_installarea_prefix)/python
nexo-offline_install_python=/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/$(nexo-offline_installarea_prefix)/python
use_requirements=requirements $(CMT_root)/mgr/requirements $(SniperRelease_root)/cmt/requirements $(DataBuffer_root)/cmt/requirements $(HelloWorld_root)/cmt/requirements $(DummyAlg_root)/cmt/requirements $(RootWriter_root)/cmt/requirements $(BufferMemMgr_root)/cmt/requirements $(RootIOSvc_root)/cmt/requirements $(RootIOUtil_root)/cmt/requirements $(EvtNavigator_root)/cmt/requirements $(SimEvent_root)/cmt/requirements $(ElecEvent_root)/cmt/requirements $(PidTmvaEvent_root)/cmt/requirements $(EDMUtil_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(BaseEvent_root)/cmt/requirements $(XmlObjDesc_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(ROOT_root)/cmt/requirements 
use_includes= $(ppcmd)"$(SniperRelease_root)/src" $(ppcmd)"$(DataBuffer_root)/src" $(ppcmd)"$(HelloWorld_root)/src" $(ppcmd)"$(DummyAlg_root)/src" $(ppcmd)"$(RootWriter_root)/src" $(ppcmd)"$(BufferMemMgr_root)/src" $(ppcmd)"$(RootIOSvc_root)/src" $(ppcmd)"$(RootIOUtil_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/RootIO/RootIOUtil/RootIOUtil" $(ppcmd)"$(EvtNavigator_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EvtNavigator/EvtNavigator" $(ppcmd)"$(SimEvent_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/SimEvent/" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/SimEvent/Event" $(ppcmd)"$(ElecEvent_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/ElecEvent/" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/ElecEvent/Event" $(ppcmd)"$(PidTmvaEvent_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/PidTmvaEvent/" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/PidTmvaEvent/Event" $(ppcmd)"$(EDMUtil_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EDMUtil/include" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/EDMUtil/EDMUtil" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(BaseEvent_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/nexo-offline/DataModel/BaseEvent/Event" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/Boost/1.55.0/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/home/hep/david_moore/zl423/NEXOTOP/ExternalLibs/ROOT/5.34.36/include" 
use_fincludes= $(use_includes)
use_stamps=  $(tutorials_stamps)  $(SniperRelease_stamps)  $(DataBuffer_stamps)  $(HelloWorld_stamps)  $(DummyAlg_stamps)  $(RootWriter_stamps)  $(BufferMemMgr_stamps)  $(RootIOSvc_stamps)  $(RootIOUtil_stamps)  $(EvtNavigator_stamps)  $(SimEvent_stamps)  $(ElecEvent_stamps)  $(PidTmvaEvent_stamps)  $(EDMUtil_stamps)  $(SniperKernel_stamps)  $(BaseEvent_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps)  $(ROOT_stamps) 
use_cflags=  $(tutorials_cflags)  $(SniperRelease_cflags)  $(DataBuffer_cflags)  $(HelloWorld_cflags)  $(DummyAlg_cflags)  $(RootWriter_cflags)  $(BufferMemMgr_cflags)  $(RootIOSvc_cflags)  $(RootIOUtil_cflags)  $(EvtNavigator_cflags)  $(SimEvent_cflags)  $(ElecEvent_cflags)  $(PidTmvaEvent_cflags)  $(EDMUtil_cflags)  $(SniperKernel_cflags)  $(BaseEvent_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags)  $(ROOT_cflags) 
use_pp_cflags=  $(tutorials_pp_cflags)  $(SniperRelease_pp_cflags)  $(DataBuffer_pp_cflags)  $(HelloWorld_pp_cflags)  $(DummyAlg_pp_cflags)  $(RootWriter_pp_cflags)  $(BufferMemMgr_pp_cflags)  $(RootIOSvc_pp_cflags)  $(RootIOUtil_pp_cflags)  $(EvtNavigator_pp_cflags)  $(SimEvent_pp_cflags)  $(ElecEvent_pp_cflags)  $(PidTmvaEvent_pp_cflags)  $(EDMUtil_pp_cflags)  $(SniperKernel_pp_cflags)  $(BaseEvent_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(ROOT_pp_cflags) 
use_cppflags=  $(tutorials_cppflags)  $(SniperRelease_cppflags)  $(DataBuffer_cppflags)  $(HelloWorld_cppflags)  $(DummyAlg_cppflags)  $(RootWriter_cppflags)  $(BufferMemMgr_cppflags)  $(RootIOSvc_cppflags)  $(RootIOUtil_cppflags)  $(EvtNavigator_cppflags)  $(SimEvent_cppflags)  $(ElecEvent_cppflags)  $(PidTmvaEvent_cppflags)  $(EDMUtil_cppflags)  $(SniperKernel_cppflags)  $(BaseEvent_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(ROOT_cppflags) 
use_pp_cppflags=  $(tutorials_pp_cppflags)  $(SniperRelease_pp_cppflags)  $(DataBuffer_pp_cppflags)  $(HelloWorld_pp_cppflags)  $(DummyAlg_pp_cppflags)  $(RootWriter_pp_cppflags)  $(BufferMemMgr_pp_cppflags)  $(RootIOSvc_pp_cppflags)  $(RootIOUtil_pp_cppflags)  $(EvtNavigator_pp_cppflags)  $(SimEvent_pp_cppflags)  $(ElecEvent_pp_cppflags)  $(PidTmvaEvent_pp_cppflags)  $(EDMUtil_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(BaseEvent_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(ROOT_pp_cppflags) 
use_fflags=  $(tutorials_fflags)  $(SniperRelease_fflags)  $(DataBuffer_fflags)  $(HelloWorld_fflags)  $(DummyAlg_fflags)  $(RootWriter_fflags)  $(BufferMemMgr_fflags)  $(RootIOSvc_fflags)  $(RootIOUtil_fflags)  $(EvtNavigator_fflags)  $(SimEvent_fflags)  $(ElecEvent_fflags)  $(PidTmvaEvent_fflags)  $(EDMUtil_fflags)  $(SniperKernel_fflags)  $(BaseEvent_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags)  $(ROOT_fflags) 
use_pp_fflags=  $(tutorials_pp_fflags)  $(SniperRelease_pp_fflags)  $(DataBuffer_pp_fflags)  $(HelloWorld_pp_fflags)  $(DummyAlg_pp_fflags)  $(RootWriter_pp_fflags)  $(BufferMemMgr_pp_fflags)  $(RootIOSvc_pp_fflags)  $(RootIOUtil_pp_fflags)  $(EvtNavigator_pp_fflags)  $(SimEvent_pp_fflags)  $(ElecEvent_pp_fflags)  $(PidTmvaEvent_pp_fflags)  $(EDMUtil_pp_fflags)  $(SniperKernel_pp_fflags)  $(BaseEvent_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(ROOT_pp_fflags) 
use_libraries= $(SniperRelease_libraries)  $(DataBuffer_libraries)  $(HelloWorld_libraries)  $(DummyAlg_libraries)  $(RootWriter_libraries)  $(BufferMemMgr_libraries)  $(RootIOSvc_libraries)  $(RootIOUtil_libraries)  $(EvtNavigator_libraries)  $(SimEvent_libraries)  $(ElecEvent_libraries)  $(PidTmvaEvent_libraries)  $(EDMUtil_libraries)  $(SniperKernel_libraries)  $(BaseEvent_libraries)  $(XmlObjDesc_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries)  $(ROOT_libraries) 
fincludes= $(includes)
tutorials_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= tutorials 
all_constituents= $(constituents)
constituentsclean= tutorialsclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
tutorialsprototype_dependencies= $(tutorialscompile_dependencies)
